Added code and dependencies for Image Translation.
geekquad/Image-Processing-OpenCV pull request #280
Opened 2021-05-21 07:54 UTC by ainy-123

Related issue.
#13 

Kindly review and merge the PR.

2021-05-22 18:48 UTC, geekquad requested changes
Hey @ainy-123, please resove the conflicts.

2021-05-22 22:38 UTC, ainy-123 commented
> Hey @ainy-123, please resolve the conflicts.

could you please help me ,how to resolve conflicts? @geekquad

2021-05-23 13:43 UTC, ainy-123 commented
> Hey @ainy-123, please resolve the conflicts.

Requested changes done, Please have a look.

2021-05-24 01:05 UTC, geekquad approved these changes

2021-05-24 01:05 UTC, merged