Color Transfer using openCV
geekquad/Image-Processing-OpenCV pull request #369
Opened 2021-05-29 18:46 UTC by mansi75

2021-05-30 03:40 UTC, geekquad requested changes
Resize all the images in a common aspect ratio.

2021-06-01 05:22 UTC, geekquad commented
You have not made the requested changes.

2021-06-01 05:50 UTC, mansi75 commented
kindly check

2021-06-03 03:58 UTC, geekquad approved these changes

2021-06-03 03:59 UTC, merged